-- ============================================================
-- SEED — dados iniciais (não são usuários fictícios, apenas conteúdo do app)
-- ============================================================

insert into public.daily_quotes (text) values
('Hoje é um ótimo dia para fazer um novo amigo.'),
('Uma surpresa pode estar mais perto do que você imagina.'),
('Seu próximo grande momento pode começar com uma pequena decisão.'),
('Sorria: alguém está pensando em você agora.'),
('A saudade de hoje é a história boa de amanhã.'),
('Reencontros acontecem quando menos se espera.'),
('Uma mensagem simples pode alegrar o dia de alguém.'),
('O que é raro de encontrar é mais fácil de guardar.'),
('Boas conversas começam com um "oi" despretensioso.'),
('Hoje é um bom dia para relembrar uma música antiga.'),
('As melhores comunidades nascem de interesses bobos.'),
('Quem cultiva amizades colhe boas histórias.'),
('Um recado inesperado pode mudar o seu dia.'),
('A nostalgia é só amor por um tempo que já passou.'),
('Você é a razão de alguém sorrir hoje.'),
('Pequenas conexões formam grandes redes.'),
('Talvez hoje seja o dia de reatar aquela amizade.'),
('Guarde este dia: ele tem algo bom escondido.'),
('As pessoas certas aparecem na hora certa.'),
('Um depoimento sincero vale mais que mil curtidas.'),
('A internet já foi mais gentil — ajude a trazer isso de volta.'),
('Hoje alguém vai visitar seu perfil só para saber de você.'),
('Uma comunidade nova pode virar sua favorita.'),
('O passado tem boas lições, mas o hoje tem boas surpresas.'),
('Compartilhar uma foto pode reviver uma lembrança inteira.'),
('Amizades verdadeiras não saem de moda.'),
('Você está a um clique de reencontrar alguém importante.'),
('Hoje é um bom dia para escrever um depoimento sincero.'),
('As melhores histórias começam num "lembra quando...".'),
('Sua energia de hoje pode inspirar outra pessoa.'),
('Um scrap simples pode alegrar a manhã de alguém.'),
('A nostalgia boa é aquela que dá vontade de recomeçar.'),
('Talvez seja hora de criar aquela comunidade que você sempre quis.'),
('Curtir um post de um amigo antigo custa um segundo e vale muito.'),
('Você tem mais amigos por perto do que imagina.'),
('Hoje o universo está a seu favor — aproveite.'),
('Uma boa playlist muda o rumo do dia.'),
('As melhores redes são feitas de gente de verdade.'),
('Talvez hoje seja o dia de atualizar seu perfil.'),
('Uma foto antiga pode contar uma história nova.'),
('O primeiro passo de uma amizade é sempre o mais simples.'),
('Reviver o passado com carinho é um jeito de cuidar do presente.'),
('Você pode ser a sorte de alguém hoje.'),
('Um sorriso de hoje pode virar uma amizade de anos.'),
('As comunidades certas encontram as pessoas certas.'),
('Hoje é um bom dia para dizer "oi, tudo bem?".'),
('Pequenos gestos online também fazem diferença.'),
('A saudade de algo bom é sinal de que valeu a pena viver.'),
('Talvez hoje alguém precise só de um recado seu.'),
('O melhor da nostalgia é poder reconstruí-la do seu jeito.');
